### ISSUE TITLE
header修改

### ISSUE THREAD

**Issue by coder0wang** [Tinywan/php-project-practice#16]
我是一直找修改videojs 的header方法;
后来找到了videojs-contrib-hls插件.
但是不知道哪里改header
我试了在
  player.ready(function() {
    this.src({
      src: file_170726,
//      type: 'application/x-mpegURL',
      withCredentials: true,
      "V-Hid": "123123",
      headers: {
        "V-Hid1": "123123"
      }
    });
  });
和
  player.ready(function() {
    for(var s in this){
      console.log("  --- "+s);
    }
    this.src({
      src: file_170726,
//      type: 'application/x-mpegURL',
      withCredentials: true,
      "V-Hid": "123123",
      headers: {
        "V-Hid1": "123123"
      }
    });
  });
 var player = videojs('my-player', options, function () {
还又其他的地方都不生效.
看您的博客上有改header
请指导一下,谢谢

**Comment by Tinywan** [comment]
@coder0wang 你好！
你可以看看我这个独立出来的DEMO：[https://github.com/Tinywan/Html5-m3u8-RTMP](https://github.com/Tinywan/Html5-m3u8-RTMP)

**Comment by coder0wang** [comment]
@Tinywan 我在你的例子里没有找到哪里可以修改header内容的啊。
看你的例子反而有了跨域问题，可以qq联系吗332548865
或者邮箱 wangyudi1@126.com
多谢帮助

**Comment by coder0wang** [comment]
@Tinywan 我找到了这段代码，但是没有找到package文件不知道如何打包
    if ("json" in options) {
        isJson = true
        headers["accept"] || headers["Accept"] || (headers["Accept"] = "application/json") //Don't override existing accept header declared by user
        if (method !== "GET" && method !== "HEAD") {
            headers["content-type"] || headers["Content-Type"] || (headers["Content-Type"] = "application/json") //Don't override existing accept header declared by user
            body = JSON.stringify(options.json)
        }
    }
<img width="1356" alt="default" src="https://user-images.githubusercontent.com/8132476/28814382-e512629e-76cf-11e7-96b6-a1d82d09ae60.png">

**Comment by Tinywan** [comment]
@coder0wang 你好！这个我也在没有进一步研究，你可以google看看。

**Comment by coder0wang** [comment]
@Tinywan 我现在用您的这个版本修改header想试一下,
(这个地方有header的赋值,应该可以加进去,我单独用官方的 xhr.headers 赋值不成功 )
但是里边的js 打包不成功,我刚刚学习打包逻辑不太熟,
求高手指导下吧,怎么打包

**Comment by Tinywan** [comment]
@coder0wang Hi
给你说了，我主要是搞服务端的，JS确实不太深入，望谅解，
